### ISSUE TITLE
Entire office cannot access Mattermost: 'Mattermost unreachable'

### ISSUE THREAD

**Issue by harrimay** [mattermost/docs#2289] opened 2018-09-18 09:06 UTC
Our entire office is having trouble connecting to Mattermost. We're all receiving the same notification - see attached screenshot. 
![screen shot 2018-09-18 at 10 05 50](https://user-images.githubusercontent.com/22278061/45676768-732ab780-bb2a-11e8-8e0d-1aba48553435.png)

Our mattermost URL is talk.impero.me

Please can you look into this.

**Comment by jasonblais** [comment] 2018-09-18 11:43
@harrimay Thank you for the report. Have you reviewed these troubleshooting steps to investigate the connection issue? https://docs.mattermost.com/install/troubleshooting.html#please-check-connection-mattermost-unreachable-if-issue-persists-ask-administrator-to-check-websocket-port

**Comment by amyblais** [comment] 2018-09-26 22:06
Closing this since the issue is resolved,

**Closed by amyblais** 2018-09-26 22:06 UTC
