### ISSUE TITLE
PDF Export of Documentation

### ISSUE THREAD

**Issue by Prodian0013** [mattermost/docs#3039] opened 2019-10-09 20:53 UTC
Unable to find a link to download the documentation in pdf format.

**Comment by amyblais** [comment] 2019-10-09 23:43
@Prodian0013 Thank you for the report, I'll close this as a duplicate of an existing Help Wanted issue https://github.com/mattermost/docs/issues/355.

**Closed by amyblais** 2019-10-09 23:43 UTC

**Comment by Prodian0013** [comment] 2019-10-10 03:33
@amyblais i was able to get a pdf i just forked the repo and used readthedocs site to generate it.

https://buildmedia.readthedocs.org/media/pdf/mattermost-docs/latest/mattermost-docs.pdf
