### ISSUE TITLE
Create a "latest version" download link

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#1958] opened 2018-04-25 19:43 UTC
Currently we're putting this on the page when we need a user to download the latest version of Mattermost server:

```
    wget https://releases.mattermost.com/X.X.X/mattermost-team-X.X.X-linux-amd64.tar.gz
```

It would be less prone to fat-fingering and easier to maintain if we were able to use this:

```
    wget https://releases.mattermost.com/latest/mattermost-team-latest-linux-amd64.tar.gz
```

**Comment by it33** [comment] 2018-05-24 02:09
This is by design as we don't want people creating automation that breaks when we do a major version release and something gets deprecated. 

That said, perhaps there's an option for downloading the latest release of the current major version. 

That would probably going into feature proposal forum though, not in issues?

**Comment by justinegeffen** [comment] 2022-01-14 07:40
This has been resolved and the documentation now includes a link to this page: https://mattermost.com/deploy/. The user just needs to copy and paste the version information. Closing. :)

**Closed by justinegeffen** 2022-01-14 07:40 UTC
