### ISSUE TITLE
Enumerating a list is broken for descending lists

### ISSUE THREAD

**Issue by cjdavis62** [mattermost/docs#2775] opened 2019-06-11 18:30 UTC
When I was writing a reply to a message (they listed issues in the format
(as one single message)
> 1. text...
> 2. text...
> 3. text...
> 4. text...

When I made a reply in the format
(as one single message)
> 4. text...
> 3. text...
> 2. text...
> 1. text...

It was printed to the screen as
> 4. text...
> 5. text...
> 6. text...
> 7. text..

**Comment by amyblais** [comment] 2019-06-12 13:00
Hi @cjdavis62, what Mattermost server version, as well as device and OS are you on?

**Comment by cjdavis62** [comment] 2019-06-13 15:25
It's Mattermost 4.2.1, and I'm working on a Windows desktop running Windows 10 version 1809 (build 17763.529)

**Comment by amyblais** [comment] 2019-06-13 16:14
Thank you, also, what server version are you on? What is the "expected" part of the issue you're seeing?

**Comment by cjdavis62** [comment] 2019-06-13 22:44
Is this what you need? (it's a bit hard to find the right place to Mattermost's about.)

Mattermost Version: 5.1.1
Database Schema Version: 5.1.0
Database: postgres
Build Hash: 77274a7aca64491a1898d4e4239158817a503a8e
EE Build Hash: f1f822d34ec7426dea87ec1193e2a969888a3a86
Webapp Build Hash: acf0c6a1ebb17feab428a01ebacbd907bc59373d
Build Date: Tue Aug 7 18:15:46 UTC 2018

What is seen in the channel (hidden most of the text for privacy):
![image](https://user-images.githubusercontent.com/8673466/59471949-c0faf480-8e0a-11e9-82f8-c15da7d03c91.png)

The text I wrote:
![image](https://user-images.githubusercontent.com/8673466/59471962-d4a65b00-8e0a-11e9-8b27-11ce3529f978.png)

**Comment by amyblais** [comment] 2019-06-13 23:02
Hi @cjdavis62, I'm not able to reproduce this on the latest server version so there may have been a bug earlier. Would you be open to upgrading to v5.11 to see if you can still reproduce the issue? You can test it out at https://community.mattermost.com if you want which is currently on the latest version.

**Comment by amyblais** [comment] 2019-06-26 13:44
We haven't received an update for a while, so I'll close this for now. Please let us know if you had a chance to upgrade your server and whether you still see this issue on a recent version.

**Closed by amyblais** 2019-06-26 13:44 UTC
