### ISSUE TITLE
Documentation on muting channels is unclear

### ISSUE THREAD

**Issue by nmatt** [mattermost/docs#3187] opened 2019-11-25 16:53 UTC
From reading the documentation on muting channels, I can't figure out the following: Does one still get (a) desktop and (b) e-mail notifications for direct mentions on a muted channel?

**Comment by justinegeffen** [comment] 2019-11-29 13:19
Thanks, @nmatt! I've made some changes to the documentation in light of this issue. Let me know if it clarifies things or you have any feedback. :)

**Comment by nmatt** [comment] 2019-11-29 20:10
Thanks @justinegeffen, however it's still not 100% clear to me. Under "Notification Preferences", there are two setting, "Mute channel" and "Ignore mentions for @channel, @here and @all". When editing "Mute channel", the description is "Muting turns off desktop, email and push notifications for this channel. The channel will not be marked as unread unless you're mentioned." My question is whether desktop/email/push notifications for _direct_ mentions (i.e. _not_ @channel etc.) are also turned off by muting the channel. This is unclear because (in my mind) when muting a channel one would still like to be notified about direct mentions, similarly to how the channel will still be marked as unread in that case ("[...] unless you're mentioned", see above). So I'd like to know the intended behavior for that case. Based on the intended behavior, I might then file a feature request or a bug report, but I'd first like to make sure what the current behavior is supposed to be.

**Comment by justinegeffen** [comment] 2019-11-29 20:13
Thanks for the additional information, @nmatt. I understand what the issue is and I'm tagging @esethna on this to further clarify.

**Comment by esethna** [comment] 2019-12-05 17:54
Thanks for bringing this up @nmatt, to clarify on this:

1. Muting a channel does not send notifications (desktop, email, push) for any mentions (whether they are channel-wide or directed at you). However, while a channel is muted if you receive a mention you will still see the channel at reduced opacity with the mention badge in the sidebar:
![image](https://user-images.githubusercontent.com/14333569/70259948-225da980-1744-11ea-9f14-ab777c835942.png)
2. The setting for "Ignore mentions for channel, here and all" overrides the preference in that channel so channel-wide mentions are not be considered mentions. So,

Example #1: If the channel was unmuted and you enabled the preference to "ignore mentions for channel, here and all", then direct mentions would still trigger notifications, but channel wide mentions would not. 
Example #2: If the channel was muted and you enable the preference to "ignore mentions for channel, here and all", then no mentions (direct or channel-wide) will trigger notifications since the channel is muted, and the channel will not show a badge counter in the sidebar unless you are directly mentioned (since channel wide mentions are ignored).

@justinegeffen feel free to make any product help text or doc changes to reflect the above since that may not be clear.

**Comment by nmatt** [comment] 2019-12-05 19:07
@esethna: Just to be sure: If a channel is muted, then the "ignore mentions for channel, here and all" setting doesn't make any difference for the muted channel, correct?

In any case, I will open a feature request to enable notification for mentions in muted channels, as that would be an important feature for me.

**Comment by nmatt** [comment] 2019-12-05 19:24
I now see that there's already a feature request on UserVoice: https://mattermost.uservoice.com/forums/306457-general/suggestions/36650401-ability-to-receive-notifications-for-muted-channel

**Comment by justinegeffen** [comment] 2019-12-06 12:10
Thanks, @esethna. I'll have some time to look at this and do testing next week and will make updates as suggested.

**Comment by justinegeffen** [comment] 2020-05-30 03:51
Hi @nmatt! The documentation has been updated as per this PR: https://github.com/mattermost/docs/pull/3189. I'm going to close this issue but please don't hesitate to reopen it should you have any questions. :)

**Closed by justinegeffen** 2020-05-30 03:51 UTC
